apiVersion: apps/v1
kind: Deployment
metadata:
  name: invidious
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: invidious
          image: "quay.io/invidious/invidious:latest-arm64"
          envFrom:
            - secretRef:
                name: invidious
          env:
            - name: INVIDIOUS_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: db-url
            - name: INVIDIOUS_CONFIG
              value: |
                check_tables: true
                external_port: 443
                domain: yt.mhu.dev
                https_only: true
                statistics_enabled: false
          livenessProbe:
            tcpSocket:
              port: 3000
          startupProbe:
            httpGet:
              path: /api/v1/comments/jNQXAC9IVRw
              port: 3000
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/v1/comments/jNQXAC9IVRw
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
            periodSeconds: 30
          ports:
            - containerPort: 3000
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
      securityContext:
        runAsNonRoot: true
        runAsUser: 1637
        runAsGroup: 1637
        seccompProfile:
          type: RuntimeDefault
