apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vaultwarden

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: vaultwarden

resources:
  - namespace.yaml
  - vaultwarden-env.sealed-secret.json
  - statefulset.yaml
  - ingress.yaml
