apiVersion: apps/v1
kind: Deployment
metadata:
  name: fleetlock
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: fleetlock
  template:
    metadata:
      labels:
        name: fleetlock
    spec:
      serviceAccountName: fleetlock
      containers:
        - name: fleetlock
          image: "quay.io/poseidon/fleetlock:v0.4.0"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              memory: 8Mi
          livenessProbe:
            httpGet:
              scheme: HTTP
              port: 8080
              path: /-/healthy
