apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fleetlock

commonLabels:
  app.kubernetes.io/name: fleetlock

resources:
  - namespace.yaml
  - cluster-role-binding.yaml
  - cluster-role.yaml
  - deployment.yaml
  - monitoring.yaml
  - role-binding.yaml
  - role.yaml
  - service-account.yaml
  - service.yaml
