apiVersion: v1
kind: Namespace
metadata:
  name: fleetlock
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"key":"node-role.kubernetes.io/control-plane","Operator":"Exists"}]'
