apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: system
  destination:
    namespace: kube-system
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://helm.cilium.io/"
    chart: cilium
    targetRevision: "1.15.7"
    helm:
      valuesObject:
        operator:
          replicas: 1
        kubeProxyReplacement: true
        k8sServiceHost: "10.0.0.200"
        k8sServicePort: 6443
        ipam:
          operator:
            clusterPoolIPv4PodCIDRList:
              - "10.42.0.0/16"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
