apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcloud-csi
spec:
  project: system
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://github.com/mhutter/gitops-mhnet.git
    targetRevision: dev
    path: apps/hcloud-csi
