apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hcloud-csi
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: system
  destination:
    namespace: kube-system
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://github.com/mhutter/gitops-mhnet.git
    targetRevision: main
    path: apps/hcloud-csi
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
