apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: system
  destination:
    namespace: ingress-nginx
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx/
    chart: ingress-nginx
    targetRevision: 4.8.0
    helm:
      valuesObject:
        controller:
          kind: DaemonSet
          service:
            type: ClusterIP
          hostPort:
            enabled: true
          ingressClassResource:
            default: true
          metrics:
            enabled: true
            service:
              annotations:
                prometheus.io/scrape: "true"
                prometheus.io/port: "10254"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
