---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: system
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - 'https://github.com/mhutter/gitops-mhnet.git'
    - 'https://kubernetes.github.io/ingress-nginx/'

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '!kube-system'
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - 'https://github.com/mhutter/gitops-mhnet.git'

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
spec:
  project: system
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: https://github.com/mhutter/gitops-mhnet.git
    targetRevision: main
    path: clusters/mhnet
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
