apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.13.2/cert-manager.yaml
  - ./clusterissuer.yaml

patches:
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: cert-manager
        annotations:
          scheduler.alpha.kubernetes.io/defaultTolerations: '[{"key":"node-role.kubernetes.io/control-plane","Operator":"Exists"}]'
