apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring
commonLabels:
  app.kubernetes.io/part-of: monitoring

resources:
  - namespace.yaml
  - grafana/
  - mimir/
  - prometheus/
  - monitors.yaml
