apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - namespace.yaml
  - prometheus.yaml
  - monitors.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: monitoring
