apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
spec:
  selector:
    matchLabels:
      operated-prometheus: "true"
  endpoints:
    - targetPort: web
    - targetPort: reloader-web
