apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sealed-secrets
commonLabels:
  app.kubernetes.io/name: sealed-secrets

resources:
  - namespace.yaml
  - https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.26.3/controller.yaml
