apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prometheus-operator

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: prometheus-operator

resources:
  - namespace.yaml
  - https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.75.1/bundle.yaml
  - clusterroles.yaml
  - monitors.yaml

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
    target:
      kind: Deployment
      name: prometheus-operator
