# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: restserver
  labels:
    app.kubernetes.io/name: docspell-restserver
    app.kubernetes.io/component: restserver
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: docspell-restserver
    app.kubernetes.io/component: restserver
  ports:
    - name: rest
      port: 7880

---
# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restserver
  labels:
    app.kubernetes.io/name: docspell-restserver
    app.kubernetes.io/component: restserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: docspell-restserver
      app.kubernetes.io/component: restserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: docspell-restserver
        app.kubernetes.io/component: restserver
    spec:
      containers:
        - name: restserver
          image: 'docker.io/docspell/restserver:v0.41.0'
          livenessProbe:
            tcpSocket:
              port: 7880
          readinessProbe:
            tcpSocket:
              port: 7880

          env:
            - name: TZ
              value: Europe/Zurich
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: DOCSPELL_SERVER_APP__ID
              value: "$(POD_NAME)"
            - name: DOCSPELL_SERVER_APP__NAME
              value: mhnet Docspell
            - name: DOCSPELL_SERVER_BASE__URL
              value: "https://dms.mhu.dev"
            - name: DOCSPELL_SERVER_INTERNAL__URL
              value: "http://restserver:7880"
            - name: DOCSPELL_SERVER_BACKEND_JDBC_URL
              value: "jdbc:postgresql://postgres:5432/docspell"
            - name: DOCSPELL_SERVER_BACKEND_JDBC_USER
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: user
            - name: DOCSPELL_SERVER_BACKEND_JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: password
            - name: DOCSPELL_SERVER_BIND_ADDRESS
              value: "0.0.0.0"
            - name: DOCSPELL_SERVER_FULL__TEXT__SEARCH_ENABLED
              value: "true"
            - name: DOCSPELL_SERVER_FULL__TEXT__SEARCH_SOLR_URL
              value: "http://solr:8983/solr/docspell"
            - name: DOCSPELL_SERVER_BACKEND_SIGNUP_MODE
              value: invite
            - name: DOCSPELL_SERVER_BACKEND_SIGNUP_NEW__INVITE__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: docspell-secret
                  key: new-invite-password
            - name: DOCSPELL_SERVER_ADMIN__ENDPOINT_SECRET
              valueFrom:
                secretKeyRef:
                  name: docspell-secret
                  key: admin-secret
            - name: DOCSPELL_SERVER_AUTH_SERVER__SECRET
              valueFrom:
                secretKeyRef:
                  name: docspell-secret
                  key: server-secret
          ports:
            - containerPort: 7880
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]

      securityContext:
        runAsNonRoot: true
        runAsUser: 22312
        runAsGroup: 22312
        seccompProfile:
          type: RuntimeDefault
