multitenancy_enabled: false
no_auth_tenant: "mhnet"

server:
  http_listen_port: 9009
  log_level: info

common:
  storage:
    backend: s3
    s3:
      endpoint: "${S3_ENDPOINT}"
      access_key_id: "${S3_ACCESS_KEY_ID}"
      secret_access_key: "${S3_SECRET_KEY}"
      bucket_name: "${S3_BUCKET}"

blocks_storage:
  storage_prefix: blocks
  bucket_store:
    sync_dir: /data/tsdb-sync
  tsdb:
    dir: /data/tsdb

activity_tracker:
  filepath: /tmp/metrics-activity.log

distributor:
  ring:
    kvstore:
      store: memberlist

ingester:
  ring:
    replication_factor: 1
    kvstore:
      store: memberlist

compactor:
  data_dir: /tmp/compactor
  sharding_ring:
    kvstore:
      store: memberlist

ruler:
  rule_path: /tmp/ruler

ruler_storage:
  storage_prefix: ruler

store_gateway:
  sharding_ring:
    replication_factor: 1

# alertmanager:
#   data_dir: /data/alertmanager
#   sharding_ring:
#     replication_factor: 1
# alertmanager_storage:
#   storage_prefix: alertmanager

usage_stats:
  enabled: false
