apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: mimir
  app.kubernetes.io/component: mimir

resources:
  - statefulset.yaml
  - service.yaml
  - s3-creds.json

configMapGenerator:
  - name: mimir-config
    files:
      - config.yaml
