apiVersion: v1
kind: Service
metadata:
  name: mimir-cluster
spec:
  clusterIP: None
  selector:
    app: mimir
  ports:
    - protocol: TCP
      port: 9009

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mimir
automountServiceAccountToken: false

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mimir
spec:
  replicas: 1
  serviceName: mimir-cluster
  selector:
    matchLabels:
      app: mimir
  template:
    metadata:
      labels:
        app: mimir
    spec:
      serviceAccountName: mimir
      containers:
        - name: mimir
          image: 'docker.io/grafana/mimir:2.12.0'
          args:
            - -config.file=/etc/mimir/config.yaml
            - -config.expand-env=true
          ports:
            - name: mimir
              containerPort: 9009
          envFrom:
            - secretRef:
                name: mimir-s3-creds
          volumeMounts:
            - name: config
              mountPath: /etc/mimir
            - name: data
              mountPath: /data
            - name: tmp
              mountPath: /tmp
          livenessProbe:
            tcpSocket:
              port: 9009
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]

      securityContext:
        runAsNonRoot: true
        runAsUser: 11300
        runAsGroup: 11300
        fsGroup: 11300
        seccompProfile:
          type: RuntimeDefault

      volumes:
        - name: tmp
          emptyDir: {}
        - name: config
          configMap:
            name: mimir-config

  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        volumeMode: Filesystem
        resources:
          requests:
            storage: 10Gi
      status:
        phase: Pending
