apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: miniflux-db
spec:
  instances: 1
  imageName: "ghcr.io/cloudnative-pg/postgresql:16.3"
  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
