apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: miniflux

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: miniflux

resources:
  - ./namespace.yaml
  - ./miniflux-env.sealed-secret.json
  - ./miniflux.yaml
  - ./ingress.yaml
