apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: httpbun

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: httpbun

resources:
  - namespace.yaml
  - deployment.yaml
  - ingress.yaml
