apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: postgres
  app.kubernetes.io/component: database

resources:
  - service.yaml
  - statefulset.yaml
