apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zitadel
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: apps
  destination:
    namespace: zitadel
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://github.com/mhutter/gitops-mhnet.git"
    targetRevision: HEAD
    path: apps/zitadel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
