apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: invidious

resources:
  - namespace.yaml
  - ./database
  - ./invidious

generators:
  - ./secrets.yaml
