apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: invidious
commonLabels:
  app.kubernetes.io/part-of: invidious

resources:
  - namespace.yaml
  - db-credentials.json
  - ./database
  - ./invidious
