apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secrets
  annotations:
    config.kubernetes.io/function: |
        exec:
          path: ksops
files:
  - ./database.sops.yaml
  - ./invidious.sops.yaml
