apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/component: prometheus

resources:
  - https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.71.2/bundle.yaml
  - clusterroles.yaml
  - prometheus.yaml

patches:
  - target:
      kind: Deployment
      name: prometheus-operator
    patch: |-
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
