---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k3s
spec:
  replicas: 1
  scrapeInterval: 15s

  # Push data to Mimir
  remoteWrite:
    - name: mimir
      url: http://mimir:9009/api/v1/push

  # Consider ALL configurations
  podMonitorNamespaceSelector: {}
  podMonitorSelector: {}
  probeNamespaceSelector: {}
  probeSelector: {}
  ruleNamespaceSelector: {}
  ruleSelector: {}
  scrapeConfigNamespaceSelector: {}
  scrapeConfigSelector: {}
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}

  enableAdminAPI: false

  serviceAccountName: prometheus
  securityContext:
    fsGroup: 2000
    runAsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
