apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.5.1/deploy/kubernetes/hcloud-csi.yml

generators:
  - ./secrets.yaml

images:
  - name: registry.k8s.io/sig-storage/csi-attacher
    newName: registry-k8s-io.apps.cloudscale-lpg-2.appuio.cloud/sig-storage/csi-attacher
  - name: registry.k8s.io/sig-storage/csi-node-driver-registrar
    newName: registry-k8s-io.apps.cloudscale-lpg-2.appuio.cloud/sig-storage/csi-node-driver-registrar
  - name: registry.k8s.io/sig-storage/csi-provisioner
    newName: registry-k8s-io.apps.cloudscale-lpg-2.appuio.cloud/sig-storage/csi-provisioner
  - name: registry.k8s.io/sig-storage/csi-resizer
    newName: registry-k8s-io.apps.cloudscale-lpg-2.appuio.cloud/sig-storage/csi-resizer
  - name: registry.k8s.io/sig-storage/livenessprobe
    newName: registry-k8s-io.apps.cloudscale-lpg-2.appuio.cloud/sig-storage/livenessprobe
