apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hcloud-csi

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: hcloud-csi

resources:
  - "https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.9.0/deploy/kubernetes/hcloud-csi.yml"
  - ./hcloud.sealed-secret.json

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
    target:
      kind: Deployment
      name: hcloud-csi-controller
