apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hcloud-csi
commonLabels:
  app.kubernetes.io/name: hcloud-csi

resources:
  - https://raw.githubusercontent.com/hetznercloud/csi-driver/v2.7.0/deploy/kubernetes/hcloud-csi.yml
  - secret.json

patches:
  - target:
      kind: Deployment
      name: hcloud-csi-controller
    patch: |-
      - op: add
        path: /spec/template/spec/tolerations
        value:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
