---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-latest
  namespace: system-upgrade
spec:
  version: v1.28.2+k3s1
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - key: node.kubernetes.io/instance-type
        operator: In
        values: ["k3s"]
  serviceAccountName: system-upgrade
  drain:
    # Continue even if there are pods that do not declare a controller.
    force: true
    # deleteLocalData and ignoreDaemonSets default to `true`
  upgrade:
    image: rancher/k3s-upgrade
