---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: upgrade-cp
  namespace: system-upgrade
spec:
  version: "v1.31.1+k3s1"
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: In
        values: ["true"]
  serviceAccountName: system-upgrade
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
      operator: Exists
  drain:
    # Continue even if there are pods that do not declare a controller.
    force: true
    # deleteLocalData and ignoreDaemonSets default to `true`
  upgrade:
    image: docker.io/rancher/k3s-upgrade

---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: upgrade-node
  namespace: system-upgrade
spec:
  version: "v1.31.1+k3s1"
  concurrency: 1
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  serviceAccountName: system-upgrade
  prepare:
    image: docker.io/rancher/k3s-upgrade
    # Wait for the `upgrade-cp` plan to finish before upgrading nodes
    args:
      - prepare
      - upgrade-cp
  drain:
    # Continue even if there are pods that do not declare a controller.
    force: true
    # deleteLocalData and ignoreDaemonSets default to `true`
  upgrade:
    image: docker.io/rancher/k3s-upgrade
