apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: grafana
  app.kubernetes.io/component: grafana

resources:
  - deployment.yaml
  - ingress.yaml
