apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: zitadel-db
spec:
  instances: 3
  imageName: "ghcr.io/cloudnative-pg/postgresql:16.3"
  enableSuperuserAccess: true

  storage:
    size: 1Gi
  monitoring:
    enablePodMonitor: true
