apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zitadel

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: zitadel

resources:
  - namespace.yaml
  - secret.json
  - database.yaml
  - zitadel.yaml
  - ingress.yaml

configMapGenerator:
  - name: zitadel-config
    files:
      - zitadel-config.yaml
