apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: psql

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: psql
  - pairs:
      app.kubernetes.io/instance: psql

resources:
  - namespace.yaml
  - barman-s3-creds.sealed-secret.json
  - database.yaml
