apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k8up
commonLabels:
  app.kubernetes.io/name: k8up

resources:
  - https://github.com/k8up-io/k8up/releases/download/k8up-4.4.3/k8up-crd.yaml
  - secret.json
