name: Tests

# yamllint disable-line rule:truthy
on: [push]

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: frenck/action-yamllint@v1

  kustomize-build:
    name: kustomize build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: kustomize build apps/cert-manager
      - run: kustomize build apps/argocd
