name: Tests

# yamllint disable-line rule:truthy
on: [push]

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: frenck/action-yamllint@v1

  kubeconform:
    name: kubeconform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate all 'apps/' with kubeconform
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install kubeconform
          ./script/kubeconform.sh
