apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  # Prevent ArgoCD removing Cilium CRs
  # see: https://docs.cilium.io/en/stable/configuration/argocd-issues/
  resource.exclusions: |
    - apiGroups:
        - cilium.io
      kinds:
        - CiliumIdentity
      clusters:
        - "*"
