apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      initContainers:
        - name: install-ksops
          image: "quay.io/viaductoss/ksops:v4.2.3"
          command: ["/bin/sh", "-c"]
          args:
            - echo "Installing KSOPS...";
              mv -v "$(which ksops)" /tools/;
              mv -v "$(which kustomize)" /tools/;
          volumeMounts:
            - mountPath: /tools
              name: tools

      containers:
        - name: argocd-repo-server
          volumeMounts:
            - mountPath: /usr/local/bin/kustomize
              name: tools
              subPath: kustomize
            - mountPath: /usr/local/bin/ksops
              name: tools
              subPath: ksops
          env:
            - name: SOPS_AGE_KEY
              valueFrom:
                secretKeyRef:
                  name: sops-age
                  key: keys.txt

      volumes:
        - name: tools
          emptyDir: {}
