apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.9.2/manifests/install.yaml
  - ingress.yaml

patches:
  - path: ./argocd-cm.patch.yaml
