apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.4/manifests/install.yaml
  - ingress.yaml

patches:
  - path: ./argocd-cm.patch.yaml

  - target:
      kind: StatefulSet
      name: argocd-application-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: 256Mi

  - target:
      kind: Deployment
      name: argocd-repo-server
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            memory: 64Mi
