apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.8.4/manifests/install.yaml

patches:
  - path: ./install-ksops.patch.yaml
  - path: ./argocd-cm.patch.yaml
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: argocd
        annotations:
          scheduler.alpha.kubernetes.io/defaultTolerations: '[{"key":"node-role.kubernetes.io/control-plane","Operator":"Exists"}]'
